### PR TITLE
Add Imgur integration

### PR DESCRIPTION
**Pull request by JaniL**
Few HY CS Department based communities have started to use Teleirc for those people who still think that IRC is the best thing ever. 🔥

Since hosting an HTTP server isn't for everyone, I decided to do something about #142.

This pull request adds a feature that uploads photos from Telegram groups to Imgur and sends the URL to their IRC channels. It uses [node-imgur](https://github.com/kaimallea/node-imgur) for communicating with Imgur's API. Using the API requires registration.

This PR doesn't include anything about the feature (how to enable it and so on) in README.md, but I could write something before merging if this feels like a good addition to the bot.

### CODE REVIEW

**Comment by JaniL** [comment]
Apparently I've messed up some indentation and missed some semicolons. I'll sort that out aswell and get my text editor to notify about them in the future.

**Comment by FruitieX** [comment]
Hey, awesome, thanks for the pull request! This could certainly become the recommended way of doing image uploads, please do edit the README.md on how to enable it!

**Comment by JaniL** [comment]
Cool! I've added the instructions to extras folder.

**Comment by mautematico** [comment]
¡Hola!

I just signed up for an imgur account to test this new feature.
I found, howerever, that 

> default album privacy is public

imagen

Is this new feature aware of that? I have not found on the files changed anything that suggest that.
If I have some free time, I'll do my best to help with this. :)

¡Gracias!

**Pull request merged**
