### PR TITLE
 Add randomness to media url.

### PR DESCRIPTION
**Pull request by Bysmyyr**
Add some (configurable) randomness to url to make url guessing much harder.
We use random base64 string with configurable length between url and filename.

### CODE REVIEW

**Comment by walliski** [comment]
:+1: for this!

**Comment by Bysmyyr** [comment]
ping?

**Comment by FruitieX** [comment]
Sorry, I should have replied earlier... Gave this some thought, figured it'd be great to hash the file contents using some hash function and use the hash as filename. That way duplicate files/stickers won't be stored more than once. I'll base those changes off of this pull request, let me see if I have time during this weekend...

**Comment by Bysmyyr** [comment]
Ok, how about taking it for now and then changing later as they are not big files?

**Comment by FruitieX** [comment]
Yeah, why not :-)

Thanks!

**Pull request merged**
