### PR TITLE
Do not highlight seen usernames when they have the same nick on irc and telegram

### PR DESCRIPTION
**Pull request by albert--**
When there is a user who is using the same username on telegram and on irc his username gets highlighted when his message is relayed to telegram.

With this fix it won't happen anymore:
IRC Username: testuser
Telegram Username: testuser

Before:
`<@testuser>: test`
After:
`<testuser>: test`

### CODE REVIEW

**Comment by Bysmyyr** [comment]
Please squash your commits to one. Check the readme about that.

**Comment by albert--** [comment]
The second commit was done after I made the pull request, I forgot to check the unit tests before submitting it.
When accepting the PR FruitieX can squash it himself: https://stackoverflow.com/a/36377634

**Comment by Bysmyyr** [comment]
Yes he can but you can also. Use the Force, mean force push

**Comment by FruitieX** [comment]
Yes please squash them in the future. Thank you!

**Pull request merged**
