### PR TITLE
Implement private messaging

### PR DESCRIPTION
**Pull request by themiron**
Implement simple private messaging support:

1. `{
    ircChan: 'bot',
    tgGroup: 'tg_username'
}`
IRC contact->bot messages will be forwarded to TG as tg_bot->tg_username.
Replies to that messages will be forwarded back to IRC contact, IRC name prefixing should be enabled.

2. `{
    ircChan: 'contact',
    tgGroup: 'tg_group'
}`
IRC contact->bot messages will be forwarded to TG as tg_bot->tg_group.
Messages from tg_group will be forwarded back to IRC contact.

### CODE REVIEW

**Comment by Bysmyyr** [comment]
looks good but fix the checks please :)

**Comment by themiron** [comment]
sure, thanks for the remind

**Comment by themiron** [comment]
@Bysmyyr have fixed my changes, but checks are still failed due unrelated pre-existing code

**Comment by themiron** [comment]
any news?

**Comment by FruitieX** [comment]
Thanks! Sorry for not responding earlier, I'm a little bit inactive here as of lately. :)

**Comment by themiron** [comment]
thanks!

**Pull request merged**
