### PR TITLE
New irc dependency

### PR DESCRIPTION
**Pull request by adedomin**
current irc dependency fails miserably when someone who isn't in the channel is unbanned

example:

00:42 -!- mode/#ghetty.space [+b *!*@nsa.gov] by prussian
00:42 -!- mode/#ghetty.space [-b *!*@nsa.gov] by prussian

would kill the bot. I changed the IRC dependency to one that I use in another bot which appears to not sporadically die.

### CODE REVIEW

**Comment by adedomin** [comment]
further testing seems to suggest the bot only dies if it isn't aware of the initial +b?
anyhow I see a lot of bots using the irc module dying for a variety of unusual reasons.

it's for the best to replace it as soon as possible.

**Comment by adedomin** [comment]
tested:

/names works from telegram. the only major difference is user modes are no longer displayed.
/topic shows the channel topic

messages are relayed
actions are relayed
notices are relayed, though they look the same as messages?
joins are relayed
parts are relayed
kicks are relayed
quits are not relayed -> due to irc-framework differences, the quit events are not relayed.

I ran `npm run test` to ensure i complied with your style guide.

if there is anything else I need to test, let me know.

**Comment by Bysmyyr** [comment]
Could you please combine those commits to one (two, max three if that is more clear)

**Comment by adedomin** [comment]
done.

**Comment by FruitieX** [comment]
Legit. I'll totally revive this project one day, and this would have been the first thing I do probably. Thanks!

**Pull request merged**
