### PR TITLE
Ignore Feature: Issue 192

### PR DESCRIPTION
**Pull request by adedomin**
for #192 

also includes a "user" ignore as well since I have some bots that output ascii art and it's just useless noise on telegram.

tested both. seems to function correctly.

### CODE REVIEW

**Comment by FruitieX** [comment]
Big thanks for the PR. Sorry for not doing anything in ages, now I merged a few other PRs and notice this one conflicts. I'll fix this in a few days unless you beat me to it.

**Comment by adedomin** [comment]
ya I'll handle it in a minute.

**Comment by Bysmyyr** [comment]
Sorry, but I like to have this squeashed to one commit with relevant commit message.

**Comment by richrd** [comment]
Nice feature! I could use this to exclude irc bot messages from telegram. Haven't tested it but looks good to me.

**Comment by FruitieX** [comment]
Merged!

**Pull request merged**
