### PR TITLE
Media captions

### PR DESCRIPTION
**Pull request by Surye**
Video and images may have a caption, append them to the URL if they exist.

### CODE REVIEW

**Comment by FruitieX** [comment]
That is a useful feature. This is just nitpicking at this point, but if there's no caption then there will always be one extra whitespace after the (Photo ...) or (Video ...) parenthesis.

Here's one way to solve that. Instead of
```
url + ' ' + (msg.caption || '')
```

you could use a *ternary operator* as such:
```
url + (msg.caption ? ' ' + msg.caption : '')
```
If you don't know these from before, the operator will test the expression before the question mark - if true it will evaluate to whatever was before the colon, if false it will evaluate to whatever is after the colon.

**Comment by Surye** [comment]
Yes, you are right, I was just being lazy on that.. Fixed :P

**Comment by Surye** [comment]
I will clean this up and create a rebased PR

**Comment by FruitieX** [comment]
Excellent, thank you for your contributions!

**Comment by FruitieX** [comment]
OK, I'll wait for that one.

**Comment by Surye** [comment]
I'm usually pretty gun-shy about rebase and any history changing operations but I'll keep it in mind for this project :) Should be good now.

**Comment by FruitieX** [comment]
Looks good.

You're right in being a little bit afraid of those operations, they do indeed destructively change history :smile:. Just keep to the "golden rule" of rebasing and everyone should be happy - that is only perform a rebase in your own branches and only if nobody else is working off of them.

**Pull request merged**
