### PR TITLE
Colorized Nicks for IRC users

### PR DESCRIPTION
**Pull request by GeneralUnRest**
I was running into readability problems when I had 5 or 6 users speaking on telegram.

So I added this colorizing feature.

### CODE REVIEW

**Comment by FruitieX** [comment]
Hey, that's an awesome feature! Thanks :)

**Comment by zertrin** [comment]
Hi, this is indeed a great feature, Thanks a lot!

However not all the colors are readable depending on the background color of the IRC client.

For example, yellow is absolutely unreadable on white background.

Would it be possible to account at least for black and white background (the two most common) and change the set of colors used a bit so that it is compatible with those two background colors at the same time.

As a minimum, I suggest to get rid of the yellow and the white.

**Comment by FruitieX** [comment]
Sounds good, we should do that.

**Comment by zertrin** [comment]
Hi, should I open a new issue concerning that or is it on your radar?

**Comment by FruitieX** [comment]
New issue is preferred, thank you

**Pull request merged**
