### PR TITLE
Show the username of telegram user with sended the message

### PR DESCRIPTION
**Pull request by jppcel**
@fczuardi and I altered the lines of the code about the show the user with send the messages on the telegram to show his username too.

### CODE REVIEW

**Comment by FruitieX** [comment]
Hi, I think it would be preferred to only show either the username or firstname. Maybe so that if the Telegram username is set then use that, otherwise use the firstname.

**Comment by Bysmyyr** [comment]
How about possibility to configure what to show?

**Comment by jppcel** [comment]
I can push a new commit with any method to configure it, if you want @Bysmyyr and @FruitieX 
With four configurations:
1 - First Name
2 - First Name and Last Name
3 - First Nama, Last Name (@username)
4 - @username

**Comment by Bysmyyr** [comment]
Thats sounds good for me but @FruitieX is the boss :P

It would be also nice if there is fully configurable string with place-holders and length limiters etc but you suggestion is good for now.

**Comment by FruitieX** [comment]
Sounds good to me too. AFAIK Telegram usernames are optional, keep that in mind when implementing the 4th option so that if the username is not set, fallback to showing the user's first name.

**Pull request merged**
