### PR TITLE
Use userName, realName and password when connecting

### LINKED ISSUE #212: config.ircOptions realName does nothing
I think this is related to https://github.com/FruitieX/teleirc/issues/207 .

### PR DESCRIPTION
**Pull request by richrd**
Connecting to servers with passwords stopped working when teleirc switched to irc-framework. This fixes the issue. Also fixes #212 and #207 .

### CODE REVIEW

**Comment by Mikaela** [comment]
Would you also be able to take a look at https://github.com/FruitieX/teleirc/issues/207 & https://github.com/FruitieX/teleirc/issues/212 which I think to be related?

I am not a coder and this looks bigger change than I am willing to merge, but I will ping others to take a look.

**Comment by richrd** [comment]
Yes. Those should be easy to add. I'll revise this PR (I noticed that it can be simplified too).

**Comment by richrd** [comment]
Done.

**Comment by Bysmyyr** [comment]
looks good, I did not tested it but I trust you :P

**Comment by richrd** [comment]
Thank you! Great to be able to run the official `develop` branch now. And now I get to benefit from the 'split-long-messages' fix :+1: :tada:

**Pull request merged**
